language: node_js
sudo: required
node_js:
  - 'node'

addons:
  apt:
    packages:
    - lftp

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn install
  - yarn generate

script:
  - echo "Skipping tests"

env:
after_success:
- lftp -e "debug; set ftps:initial-prot ''; set ftp:ssl-force true; set ftp:ssl-protect-data true; set ssl:verify-certificate/$fingerprint no ; open $user:$password@$server:21 ; mirror -R --only-newer --delete -v $TRAVIS_BUILD_DIR/dist . ; quit"