language: node_js
node_js:
  - 'node'

addons:
  apt:
    packages:
    - lftp

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - yarn install
  - yarn generate

script:
  - echo "Skipping tests"

env:
after_success:
- lftp -e "debug ; set ssl:verify-certificate no ; mirror -R --only-newer --delete -v dist / ; bye" -u ${user},${password} ftp://${server}