language: node_js
node_js:
  - '8'

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

env:
  global:
  - 'SFTP_USER=[user]'
  - 'SFTP_PASSWORD=[password]'
after_success:
- find /dist/ -exec curl -T {} ftp://public_html/www_btree_at/deploy/ --user ${SFTP_USER}:${SFTP_PASSWORD} \;